# Generated by Django 2.1.7 on 2019-04-03 02:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
                ('site_id', models.CharField(blank=True, max_length=20, null=True)),
                ('description', models.TextField(max_length=500, null=True)),
                ('latitude', models.FloatField(default=33.88, null=True)),
                ('longitude', models.FloatField(default=-101.22, null=True)),
                ('is_published', models.BooleanField(default=False, null=True)),
                ('post_date', models.DateTimeField(default=datetime.datetime.now, null=True)),
            ],
        ),
    ]
