# Generated by Django 2.1.7 on 2019-04-04 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metload', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='obsset',
            name='sunrise',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='obsset',
            name='sunset',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
