# Generated by Django 2.1.7 on 2019-04-06 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metload', '0003_auto_20190406_0037'),
    ]

    operations = [
        migrations.AlterField(
            model_name='obsset',
            name='sunrise',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='obsset',
            name='sunset',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=20, null=True),
        ),
    ]
